### ISSUE TITLE
win10 运行必须要保存文件吗

### ISSUE THREAD

**Issue by world-dream** [xxyjskx1987/MathLabTool#1]
win10 运行code提示保存文件，输入文件名保存一直失败

**Comment by xxyjskx1987** [comment]
截图看下问题，要保存文件没做临时文件的功能，可以先做个js文件打开试试。

**Comment by world-dream** [comment]
> Reference in new issue
![Uploading test.png…]()

**Comment by world-dream** [comment]
截图

**Comment by world-dream** [comment]
> 截图看下问题，要保存文件没做临时文件的功能，可以先做个js文件打开试试。
> 

![7bf67ddcc46105a97d0caa7a2cea3e87_1702973275065_wm.png](https://github.com/xxyjskx1987/MathLabTool/assets/29618136/ff610f4e-5218-4613-98b8-ec2bdea6b34d)

**Comment by xxyjskx1987** [comment]
我试了一下本地安装没问题，你在打开软件的时候提示给权限给了么？在cmd中试试wmic logicaldisk get caption这个指令，这是代码中获取磁盘路径的指令。

**Comment by world-dream** [comment]
好的，应该是安装授权的问题

**Comment by xxyjskx1987** [comment]
OK，那我把问题关闭了，有问题再开。

**Comment by xxyjskx1987** [comment]
https://github.com/xxyjskx1987/MathLabTool/releases/tag/v0.0.5-beta
新增：脚本在不保存情况下也可运行（简单eval实现）
